### PR TITLE
Add support for a progress meter

### PR DESCRIPTION
**Pull request by alch-emi**
As discussed in ManeChat

### CODE REVIEW

**Comment by alch-emi** [comment]
~~wait fuck don't merge this~~

**Comment by alch-emi** [comment]
missed a spot

**Comment by alch-emi** [comment]
k now its good

**Comment by alch-emi** [comment]
oh frick there's a merge conflict now, gimme a sec

**Review by Bigcheese — APPROVED** [review]
LGTM, ship it!

**Pull request merged**
